export interface ToolDefinition {
  slug: string;
  name: string;
  /** Canonical English URL for this tool (e.g., '/image/png-to-svg') */
  href: string;
  tagline: string;
  description: string;
  keywords: string[];
  icon: string;
  category: 'image' | 'document' | 'pdf' | 'audio' | 'video' | 'data';
  isClientSide: boolean;
  comingSoon?: boolean;
}

export const tools: ToolDefinition[] = [
  {
    slug: 'vectorizer',
    name: 'Image to SVG Vectorizer',
    href: '/image/png-to-svg',
    tagline: 'Convert PNG & JPG to scalable vector graphics',
    description:
      'Free online PNG to SVG converter. Transform raster images into clean, scalable vector graphics instantly — right in your browser. No upload required, 100% private.',
    keywords: [
      'png to svg',
      'jpg to svg',
      'image to svg converter',
      'vectorize image',
      'image vectorizer',
      'convert png to vector',
      'raster to vector',
      'free svg converter',
    ],
    icon: 'sparkles',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'remove-background',
    name: 'Background Remover',
    href: '/image/remove-background',
    tagline: 'Remove image backgrounds with AI — locally',
    description:
      'Free online background remover powered by AI. Remove backgrounds from photos instantly using WebGPU — 100% in your browser. No upload, no signup.',
    keywords: [
      'remove background',
      'background remover',
      'remove bg',
      'transparent background',
      'remove image background',
      'background eraser',
      'free background remover',
    ],
    icon: 'wand',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'pdf-merge',
    name: 'PDF Merge',
    href: '/pdf/merge',
    tagline: 'Combine multiple PDFs into one file',
    description:
      'Free online PDF merger. Drag, drop, reorder, and merge unlimited PDF files — 100% in your browser. No upload, no signup.',
    keywords: ['merge pdf', 'combine pdf', 'join pdf', 'pdf merger'],
    icon: 'file-plus',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'pdf-split',
    name: 'PDF Split',
    href: '/pdf/split',
    tagline: 'Split PDF by pages, ranges, or equal parts',
    description:
      'Free online PDF splitter. Extract pages, split every N pages, or divide into equal parts — entirely in your browser.',
    keywords: ['split pdf', 'extract pdf pages', 'pdf splitter', 'separate pdf'],
    icon: 'scissors',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    href: '/image/compress-image',
    tagline: 'Reduce image file size without quality loss',
    description:
      'Free online image compressor. Reduce PNG, JPG, and WebP file sizes while maintaining visual quality — 100% in your browser. No upload, no signup.',
    keywords: [
      'image compressor',
      'compress png',
      'compress jpg',
      'compress webp',
      'reduce image size',
      'image optimizer',
      'compress image online',
      'free image compressor',
    ],
    icon: 'minimize',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'coloring-page',
    name: 'Photo to Coloring Page',
    href: '/image/photo-to-coloring-page',
    tagline: 'Turn any photo into a printable coloring page',
    description:
      'Free online photo to coloring page converter. Transform photographs into clean line art for kids, teachers, and KDP creators — 100% in your browser.',
    keywords: [
      'photo to coloring page',
      'coloring page generator',
      'image to coloring page',
      'coloring book maker',
      'line art converter',
      'photo to line drawing',
      'free coloring page',
      'printable coloring page',
    ],
    icon: 'palette',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'audio-converter',
    name: 'Audio Converter',
    href: '/audio/convert-audio',
    tagline: 'Convert between MP3, WAV, OGG, FLAC, AAC',
    description:
      'Free online audio converter. Convert, compress, and trim audio files — MP3, WAV, OGG, FLAC, AAC. 100% in your browser using FFmpeg WASM.',
    keywords: [
      'audio converter',
      'mp3 converter',
      'convert wav to mp3',
      'audio format converter',
      'ogg to mp3',
      'flac to mp3',
      'audio trimmer',
      'free audio converter',
    ],
    icon: 'music',
    category: 'audio',
    isClientSide: true,
  },
  {
    slug: 'speech-to-text',
    name: 'Speech to Text',
    href: '/audio/speech-to-text',
    tagline: 'Transcribe audio with Whisper AI — locally',
    description:
      'Free online speech-to-text transcription powered by Whisper AI. Transcribe audio and video files to text with timestamps. 100% in your browser — no upload.',
    keywords: [
      'speech to text',
      'audio transcription',
      'whisper ai',
      'transcribe audio',
      'audio to text',
      'voice to text',
      'free transcription',
      'subtitle generator',
    ],
    icon: 'mic',
    category: 'audio',
    isClientSide: true,
  },
  {
    slug: 'image-converter',
    name: 'Image Converter',
    href: '/image/format-converter',
    tagline: 'Convert HEIC, WebP, AVIF to JPG, PNG, WebP',
    description:
      'Free online image format converter. Convert HEIC, WebP, AVIF, BMP, GIF, and TIFF to JPG, PNG, or WebP — 100% in your browser. No upload, no signup.',
    keywords: [
      'image converter',
      'heic to jpg',
      'webp to jpg',
      'webp to png',
      'avif to jpg',
      'convert image format',
      'image format converter',
      'free image converter',
    ],
    icon: 'refresh-cw',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'pdf-password',
    name: 'PDF Password Protect',
    href: '/pdf/password-protect',
    tagline: 'Add password protection to any PDF',
    description:
      'Free online PDF password protection. Encrypt any PDF with a password — 100% in your browser. No upload, no signup.',
    keywords: [
      'pdf password protect',
      'encrypt pdf',
      'password protect pdf',
      'pdf security',
      'lock pdf',
      'pdf encryption',
      'free pdf password',
    ],
    icon: 'lock',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'images-to-pdf',
    name: 'Images to PDF',
    href: '/pdf/images-to-pdf',
    tagline: 'Convert images to a multi-page PDF',
    description:
      'Free online image to PDF converter. Drag, drop, and reorder JPG, PNG, or WebP images to create a multi-page PDF — 100% in your browser. No upload, no signup.',
    keywords: [
      'images to pdf',
      'jpg to pdf',
      'png to pdf',
      'photo to pdf',
      'convert images to pdf',
      'image to pdf converter',
      'combine images into pdf',
    ],
    icon: 'image-plus',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'pdf-watermark',
    name: 'PDF Watermark',
    href: '/pdf/watermark',
    tagline: 'Add text watermark to any PDF',
    description:
      'Free online PDF watermark tool. Add custom text watermarks like CONFIDENTIAL or DRAFT to every page — 100% in your browser. No upload, no signup.',
    keywords: [
      'pdf watermark',
      'add watermark to pdf',
      'stamp pdf',
      'pdf watermark online',
      'watermark pdf free',
    ],
    icon: 'droplets',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'pdf-page-numbers',
    name: 'PDF Page Numbers',
    href: '/pdf/page-numbers',
    tagline: 'Add page numbers to any PDF',
    description:
      'Free online tool to add page numbers to PDF documents. Choose position, format, and starting number — 100% in your browser.',
    keywords: [
      'add page numbers to pdf',
      'pdf page numbers',
      'number pdf pages',
      'pdf page numbering',
    ],
    icon: 'hash',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'image-resize',
    name: 'Image Resize',
    href: '/image/resize',
    tagline: 'Resize and crop images to any dimensions',
    description:
      'Free online image resizer. Resize to custom dimensions, percentages, or social media presets. Export as PNG, JPG, or WebP — 100% in your browser.',
    keywords: [
      'resize image',
      'crop image',
      'image resizer',
      'resize image online',
      'resize for instagram',
      'photo resizer',
    ],
    icon: 'maximize',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'image-base64',
    name: 'Image to Base64',
    href: '/image/base64',
    tagline: 'Encode images to Base64 or decode Base64 to images',
    description:
      'Free online Image to Base64 encoder and decoder. Convert images to data URIs for embedding in HTML/CSS — 100% in your browser.',
    keywords: [
      'image to base64',
      'base64 to image',
      'base64 encoder',
      'data uri converter',
      'base64 image converter',
    ],
    icon: 'code',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'video-to-gif',
    name: 'Video to GIF',
    href: '/image/video-to-gif',
    tagline: 'Convert video clips to animated GIFs',
    description:
      'Free online video to GIF converter. Trim, set FPS and size, then convert MP4, WebM, or MOV to high-quality animated GIFs — 100% in your browser.',
    keywords: [
      'video to gif',
      'mp4 to gif',
      'convert video to gif',
      'gif maker',
      'video to gif converter',
    ],
    icon: 'film',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'qr-code',
    name: 'QR Code Generator',
    href: '/tools/qr-code-generator',
    tagline: 'Generate QR codes for URLs, text, and WiFi',
    description:
      'Free online QR code generator. Create QR codes for links, text, WiFi credentials, and more. Download as PNG or SVG — 100% in your browser.',
    keywords: [
      'qr code generator',
      'create qr code',
      'qr code maker',
      'qr code free',
      'generate qr code',
    ],
    icon: 'qr-code',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'sign-pdf',
    name: 'Sign PDF',
    href: '/pdf/sign',
    tagline: 'Add your signature to any PDF',
    description:
      'Free online PDF signer. Draw your signature and place it on any page — 100% in your browser. No upload, no signup.',
    keywords: [
      'sign pdf',
      'sign pdf online',
      'add signature to pdf',
      'e-sign pdf',
      'pdf signature',
    ],
    icon: 'pen-tool',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'pdf-form-filler',
    name: 'PDF Form Filler',
    href: '/pdf/fill-form',
    tagline: 'Fill out PDF forms online',
    description:
      'Free online PDF form filler. Detect and fill text fields, checkboxes, and dropdowns in any PDF — 100% in your browser.',
    keywords: [
      'fill pdf form',
      'pdf form filler',
      'edit pdf form',
      'fill pdf online',
    ],
    icon: 'clipboard-list',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'pdf-to-images',
    name: 'PDF to Images',
    href: '/pdf/to-images',
    tagline: 'Convert PDF pages to images',
    description:
      'Free online PDF to image converter. Extract every page as a PNG or JPG. Choose DPI quality — 100% in your browser.',
    keywords: [
      'pdf to image',
      'pdf to png',
      'pdf to jpg',
      'convert pdf to image',
      'extract pdf pages',
    ],
    icon: 'file-image',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'ocr',
    name: 'OCR — Image to Text',
    href: '/image/ocr',
    tagline: 'Extract text from images using OCR',
    description:
      'Free online OCR tool. Extract text from photos, screenshots, and scanned documents. Supports 10 languages — 100% in your browser.',
    keywords: [
      'ocr',
      'image to text',
      'extract text from image',
      'ocr online',
      'photo to text',
    ],
    icon: 'scan-text',
    category: 'image',
    isClientSide: true,
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    href: '/tools/word-counter',
    tagline: 'Count words, characters, sentences & reading time',
    description: 'Free online word counter. Count words, characters, sentences, paragraphs. Estimate reading and speaking time — instantly in your browser.',
    keywords: ['word counter', 'character counter', 'word count', 'character count', 'text counter', 'letter counter'],
    icon: 'hash',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'case-converter',
    name: 'Case Converter',
    href: '/tools/case-converter',
    tagline: 'Convert text case — upper, lower, title & more',
    description: 'Free online case converter. Change text to uppercase, lowercase, title case, sentence case, and more — instantly in your browser.',
    keywords: ['case converter', 'uppercase converter', 'lowercase converter', 'title case', 'text case changer'],
    icon: 'case-sensitive',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'lorem-ipsum',
    name: 'Lorem Ipsum Generator',
    href: '/tools/lorem-ipsum',
    tagline: 'Generate placeholder text for designs',
    description: 'Free Lorem Ipsum generator. Generate paragraphs, sentences, or words of placeholder text for your designs and layouts.',
    keywords: ['lorem ipsum generator', 'placeholder text', 'dummy text generator', 'lorem ipsum'],
    icon: 'align-left',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'text-to-pdf',
    name: 'Text to PDF',
    href: '/tools/text-to-pdf',
    tagline: 'Convert plain text to PDF documents',
    description: 'Free online text to PDF converter. Type or paste text, choose font and size, then download as a formatted PDF — 100% in your browser.',
    keywords: ['text to pdf', 'convert text to pdf', 'txt to pdf', 'notepad to pdf'],
    icon: 'file-text',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    href: '/tools/json-formatter',
    tagline: 'Format, validate & minify JSON',
    description: 'Free online JSON formatter and validator. Pretty-print, minify, and validate JSON data — instantly in your browser.',
    keywords: ['json formatter', 'json validator', 'json beautifier', 'json viewer', 'format json', 'json pretty print'],
    icon: 'braces',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'color-picker',
    name: 'Color Picker',
    href: '/tools/color-picker',
    tagline: 'Pick colors & convert HEX, RGB, HSL',
    description: 'Free online color picker. Pick any color and convert between HEX, RGB, and HSL formats — copy to clipboard instantly.',
    keywords: ['color picker', 'hex to rgb', 'rgb to hex', 'color converter', 'hex color picker', 'hsl to hex'],
    icon: 'palette',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'url-encoder',
    name: 'URL Encoder / Decoder',
    href: '/tools/url-encoder',
    tagline: 'Encode or decode URLs and query strings',
    description: 'Free online URL encoder and decoder. Encode special characters for URLs or decode percent-encoded strings — instantly in your browser.',
    keywords: ['url encoder', 'url decoder', 'encode url', 'decode url', 'percent encoding', 'url encode online'],
    icon: 'link',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'base64-text',
    name: 'Base64 Text Encoder',
    href: '/tools/base64-text',
    tagline: 'Encode or decode Base64 text',
    description: 'Free online Base64 encoder and decoder for text. Convert text to Base64 or decode Base64 strings — supports UTF-8.',
    keywords: ['base64 encode', 'base64 decode', 'base64 text', 'text to base64', 'base64 converter'],
    icon: 'binary',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    href: '/tools/password-generator',
    tagline: 'Generate secure random passwords',
    description: 'Free password generator. Create strong, random passwords with customizable length and character types. Uses crypto-secure randomness.',
    keywords: ['password generator', 'random password', 'strong password', 'secure password generator'],
    icon: 'key-round',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'pdf-rotate',
    name: 'PDF Rotate Pages',
    href: '/pdf/rotate',
    tagline: 'Rotate PDF pages by 90°, 180° or 270°',
    description: 'Free online PDF page rotator. Rotate all or specific pages by 90, 180, or 270 degrees — 100% in your browser.',
    keywords: ['rotate pdf', 'pdf rotate pages', 'rotate pdf online', 'pdf page rotation'],
    icon: 'rotate-cw',
    category: 'pdf',
    isClientSide: true,
  },
  {
    slug: 'diff-checker',
    name: 'Diff Checker',
    href: '/tools/diff-checker',
    tagline: 'Compare two texts and find differences',
    description: 'Free online diff checker. Compare two text inputs side-by-side and see additions, deletions, and unchanged lines.',
    keywords: ['diff checker', 'text compare', 'compare text online', 'find differences'],
    icon: 'diff',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    href: '/tools/hash-generator',
    tagline: 'Generate SHA-1, SHA-256, SHA-512 hashes',
    description: 'Free online hash generator. Compute SHA-1, SHA-256, SHA-384, and SHA-512 hashes using the Web Crypto API — 100% in your browser.',
    keywords: ['hash generator', 'sha256', 'sha512', 'sha1 hash', 'hash online'],
    icon: 'hash',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    href: '/tools/regex-tester',
    tagline: 'Test regular expressions with live matching',
    description: 'Free online regex tester. Write regular expressions and see matches highlighted in real time. Supports all JavaScript regex flags.',
    keywords: ['regex tester', 'regex online', 'regular expression tester', 'regex debugger'],
    icon: 'code',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'csv-json',
    name: 'CSV ↔ JSON Converter',
    href: '/tools/csv-json',
    tagline: 'Convert between CSV and JSON formats',
    description: 'Free CSV to JSON and JSON to CSV converter. Bidirectional conversion with proper escaping — instantly in your browser.',
    keywords: ['csv to json', 'json to csv', 'csv json converter', 'convert csv'],
    icon: 'arrow-left-right',
    category: 'data',
    isClientSide: true,
  },
  {
    slug: 'markdown-html',
    name: 'Markdown ↔ HTML',
    href: '/tools/markdown-html',
    tagline: 'Convert between Markdown and HTML',
    description: 'Free Markdown to HTML and HTML to Markdown converter. Bidirectional conversion with support for headers, bold, italic, links, and lists.',
    keywords: ['markdown to html', 'html to markdown', 'markdown converter', 'md to html'],
    icon: 'code',
    category: 'data',
    isClientSide: true,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getActiveTools(): ToolDefinition[] {
  return tools.filter((t) => !t.comingSoon);
}

export function getAllTools(): ToolDefinition[] {
  return tools;
}
